replicaCount: 1

image:
  repository: redis
  tag: 4.0.10
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379


resources:
  requests:
    memory: 10M
    cpu: 8m
  limits:
    memory: 1000M
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
