replicaCount: 1

image:
  repository: redis
  tag: 4.0.10
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379


resources:
  requests:
    cpu: 250m
  limits:
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
