replicaCount: 1

image:
  repository: mongo
  tag: 3.6.5-jessie
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017


resources:
  requests:
    cpu: 250m
  limits:
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
