{{- $name := include "payment-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "payment-api.name" . }}
    chart: {{ template "payment-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: "9d6833d8-eb9d-4ba2-8b6f-f201e435eaea"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
