replicaCount: 1

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5672


resources:
  requests:
    cpu: 75m
  limits:
    cpu: 140m

nodeSelector: {}

tolerations: []

affinity: {}
