apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.status }}
  labels:
    app: {{ template "webstatus.name" . }}
    chart: {{ template "webstatus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000
      protocol: TCP
      targetPort: 8000
      name: metrics
  selector:
    app: {{ template "webstatus.name" . }}
    release: {{ .Release.Name }}
