{{- $name := include "locations-api.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $mongo := include "mongo-name" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "locations-api.name" . }}
    chart: {{ template "locations-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: "9d6833d8-eb9d-4ba2-8b6f-f201e435eaea"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
  all_EnableLoadTest: "{{ .Values.inf.misc.useLoadTest }}"
  internalurls__IdentityUrl: http://{{ .Values.app.svc.identity }}
  urls__IdentityUrl: {{ $identity }}
  locations__ConnectionString: mongodb://{{ $mongo }}
  locations__Database: {{ .Values.inf.mongo.locations.database }}
