replicaCount: 1

image:
  repository: microsoft/mssql-server-linux
  tag: 2017-CU7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1433

resources:
  requests:
    memory: 1000M
    cpu: 50m
  limits:
    memory: 3000M
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
